app2/urls.py
from django.urls import path
from app2.views import *
app_name='something'
urlpatterns=[
    path('two/', two, name='two'), 
]

app3/urls.py
from django.urls import path 
from app3.views import *
app_name='nothing'
urlpatterns=[
    path('three/', three, name='three'), 
]

project9/urls.py
from django.contrib import admin
from django.urls import path, include
from app1.views import *
from app2.views import *
from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('one/', one, name='one'),
    path('something/', include('app2.urls')), 
    path('nothing/', include('app3.urls')),  
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def one(request):
    return render(request, 'one.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def two(request):
    return render(request, 'two.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def three(request):
    return render(request, 'three.html')

templates/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1>One Html</h1>
        <a href="{% url 'something:two' %}">Go To App2 Two.html</a>
    </center>
</body>
</html>

templates/three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Three Html</h1>
        <a href="{% url 'one' %}">Go To App1 Html</a>
    </center>
</body>
</html>

templates/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Two Html</h1>
        <a href="{% url 'nothing:three' %}">Go To App1 One.html</a>
    </center>
</body>
</html>